server:
    port: 8081

spring.datasource:
    url: ${LH_SQL}:${LH_PORT}/${LH_DB_NAME}
    username: ${LH_USERNAME}
    password: ${LH_PASS}
spring.jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update

hibernate:
    temp:
        use_jdbc_metadata_defaults: false

hibernate.connection.driver_class: com.mysql.jdbc.Driver

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE